FORMAT: 1A
HOST: https://bookameal0.herokuapp.com/docs/

# Book A Meal API

**Book A Meal** is a simple API to help in placing of orders and management of a small restaurant.
The customers are supposed to create accounts which they can use later to view menus or place orders
for meals The Restaurant staff/caterers use priviledged user accounts which allow them to modify, delete some resources

# Allowed HTTP Method
+ POST    : To create Users, Meals, Menus, Orders and Login
+ PUT     : To edit meals, orders
+ GET     : To get a resources: Meals, Menus, Orders
+ DELETE  : To delete resource: Meals

# Usual Server Responses:

* 200 OK - the request was successful

* 201 Created - the request was successful and a resource was created.

* 202 Accepted - the request 

* 400 Bad Request - the request could not be understood or was missing required parameters.

* 401 Unauthorized - authentication failed or user doesn't have permissions for requested operation.

* 404 Not Found - resource was not found.

    


## User Registration  [/v1/auth/signup]

### SIGN UP [POST]

Create new user accounts by providing a username, email and password as a JSON object

+ Request (application/json)

        {
            "username": "joseph",
            "email": "joseph@bam.com,
            "password": "test1234"
        }

+ Response 201 (application/json)

        {
            "message": "User registration succesful, proceed to login"
        }


## Login Resource [/v1/auth/signin/]
### SIGN IN [POST]

+ Request (application/json)

        {
            "username": "joseph",
            "password": "test1234"
        }
        
+ Response 201 (application/json)

        {
            "message": "User registration succesful, proceed to login",
            "access_token": 
        }