"""empty message

Revision ID: 36c4bdbf7f79
Revises: f4b7a0c53b1c
Create Date: 2018-06-26 05:48:02.498244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c4bdbf7f79'
down_revision = 'f4b7a0c53b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_meals_meal_id_fkey', 'menu_meals', type_='foreignkey')
    op.create_foreign_key(None, 'menu_meals', 'meal', ['meal_id'], ['meal_id'], ondelete='CASCADE')
    op.add_column('order', sa.Column('is_served', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.drop_column('order', 'is_served')
    op.drop_constraint(None, 'menu_meals', type_='foreignkey')
    op.create_foreign_key('menu_meals_meal_id_fkey', 'menu_meals', 'meal', ['meal_id'], ['meal_id'])
    # ### end Alembic commands ###
