"""empty message

Revision ID: 9109538f290e
Revises: 36c4bdbf7f79
Create Date: 2018-07-31 19:40:14.220774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9109538f290e'
down_revision = '36c4bdbf7f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'default')
    # ### end Alembic commands ###
